### ISSUE TITLE
版本1.1.0-BTC 无规律退出

### ISSUE THREAD

**Issue by liyachvn** [GoMinerProxy/GoMinerProxy-BTC#2]
此版本有无规律退出的情况，且退出后重新执行命令会报错（附图），再次执行命令可能又好了。
或者运行后按Ctrl-C中断，再次运行即报错，第三次运行又可以了……
希望作者修复~感谢~ 
![image](https://user-images.githubusercontent.com/63252104/162585892-9d7e6508-fe45-4f65-9180-ec479d59b75d.png)

**Comment by GoMinerProxy** [comment]
伺服器性能过低
